version: '3.1'

networks:
  genbi:
    driver: bridge

services:
  proxy:
    image: envoyproxy/envoy-alpine:v1.14.3
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - /etc/letsencrypt/:/etc/letsencrypt
    command: envoy -c /etc/envoy/envoy.yaml
    extra_hosts:
      - "myhost:10.128.0.3"
    networks:
      - genbi